# Generated by Django 2.0 on 2017-12-25 00:50

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=None, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('tags', models.TextField(blank=True, null=True)),
                ('proof_description', models.TextField(blank=True, default=None, null=True)),
                ('proof_pic', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('days_taken', models.IntegerField(blank=True, default=None, null=True)),
                ('comments', models.ManyToManyField(blank=True, related_name='comments', to='posts.Comment')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=None, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('verifications', models.ManyToManyField(blank=True, related_name='verfs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
