# Generated by Django 2.0 on 2017-12-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20171219_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='proof_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
