# Generated by Django 2.0 on 2017-12-23 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20171219_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='verifications',
            field=models.ManyToManyField(blank=True, related_name='verfs', to=settings.AUTH_USER_MODEL),
        ),
    ]
