# Generated by Django 2.0.1 on 2018-01-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20180105_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='days_taken',
        ),
        migrations.AddField(
            model_name='post',
            name='proved_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
