# Generated by Django 2.0 on 2018-01-17 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0011_auto_20180106_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('progress_pic', models.ImageField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='motivations',
            field=models.ManyToManyField(blank=True, related_name='motivations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postprogress',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Post'),
        ),
    ]
