# Generated by Django 2.0 on 2018-01-17 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20180117_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='postprogress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
