# Generated by Django 2.0 on 2017-12-28 16:23

from django.db import migrations, models
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='work',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=django_fields.fields.DefaultStaticImageField(blank=True, default='https://peerspace.herokuapp.com/media/default_profile_pic.svg', upload_to=''),
        ),
    ]
