# Generated by Django 2.0 on 2017-12-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171211_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferencetag',
            name='weight',
            field=models.DecimalField(decimal_places=5, default=0.5, max_digits=10),
        ),
    ]
