# Generated by Django 2.0 on 2017-12-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171228_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lives_in',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
