# Generated by Django 2.0 on 2017-12-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_lives_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lives_in',
            new_name='location',
        ),
    ]
