# Generated by Django 2.0 on 2017-12-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171214_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferencetag',
            name='tag',
            field=models.CharField(max_length=100),
        ),
    ]
