# Generated by Django 2.0 on 2018-01-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completion_index',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
