# Generated by Django 2.0 on 2017-12-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
