# Generated by Django 2.0 on 2018-01-02 12:35

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_completion_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=django_fields.fields.DefaultStaticImageField(blank=True, default='/media/default_profile_pic.svg', upload_to=''),
        ),
    ]
