# Generated by Django 2.0 on 2017-12-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_cover_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_pic',
            field=models.ImageField(blank=True, default='/media/default_cover_pic.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/media/default_profile_pic.jpg', upload_to=''),
        ),
    ]
