# Generated by Django 2.0 on 2017-12-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20171224_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/media/default_profile_pic.svg', upload_to=''),
        ),
    ]
