# Generated by Django 2.0.1 on 2018-01-04 20:36

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180104_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_pic',
            field=django_fields.fields.DefaultStaticImageField(blank=True, default='/default_cover_pic.jpg', upload_to=''),
        ),
    ]
