# Generated by Django 2.0.1 on 2018-01-04 20:48

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180104_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_pic',
            field=django_fields.fields.DefaultStaticImageField(blank=True, default='http://peerspace.s3.amazonaws.com/default_profile_pic.svg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=django_fields.fields.DefaultStaticImageField(blank=True, default='http://peerspace.s3.amazonaws.com/default_profile_pic.svg', upload_to=''),
        ),
    ]
