# Generated by Django 2.0 on 2018-01-02 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('redirect_url', models.URLField()),
                ('user', models.ForeignKey(on_delete=None, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
