# Generated by Django 2.0 on 2018-01-02 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0005_auto_20180102_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='user_rx',
            field=models.ForeignKey(default=None, on_delete=None, related_name='notifications_rx', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_tx',
            field=models.ForeignKey(default=None, on_delete=None, related_name='notifications_tx', to=settings.AUTH_USER_MODEL),
        ),
    ]
