# Generated by Django 2.0 on 2018-01-02 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20180102_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_rx',
            field=models.ForeignKey(on_delete=None, related_name='notifications_rx', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_tx',
            field=models.ForeignKey(on_delete=None, related_name='notifications_tx', to=settings.AUTH_USER_MODEL),
        ),
    ]
