# Generated by Django 2.0 on 2018-01-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20180102_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='text',
        ),
    ]
