# Generated by Django 2.0 on 2018-01-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_auto_20180105_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='progress_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='progress_pic_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
