# Generated by Django 2.0 on 2018-01-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_auto_20180117_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='progress_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='progress_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
