# Generated by Django 2.0 on 2018-01-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_auto_20180117_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='progress_id',
        ),
    ]
